### PR TITLE
fix sendWithPromise() doesn't send

### LINKED ISSUE #9736: qx.io.request.AbstractRequest sendWithPromise() doesn't send
**Describe the bug**
I used the new sendWithPromise() function in a project and waited forever to settle. It turns out it wasn't sending the request.

**To Reproduce**
Use `sendWithPromise()` in a `qx.io.request.Xhr`. Wait for the result's to come. The request is not even sent. No trace of the communication in browser's network tab in the developer tools.

**Expected behavior**
Returned promise should settle after a while.

### PR DESCRIPTION
**Pull request by voger**
Fixes #9736 

Also refactored the `sendWithPromise()` related tests so they are not nested inside an if condition.

### CODE REVIEW

**Review by derrell — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Comment by voger** [comment]
Please don't merge it yet. I noticed it doesn't detect network errors, CORS errors etc. I am writing a new commit and I will test it more with my project. Sorry about that.

**Comment by hkollmann** [comment]
I added the label "do not merge" for you!

**Review by johnspackman — APPROVED** [review]

**Comment by voger** [comment]
It is ready now. The tests all pass and I used it in a project. It works OK. It doesn't listen to the `changePhase` event any more but to the various events that are emited during the request cycle. This provides more reliable error handling.

**Comment by cboulanger** [comment]
@voger Could you fix the following two lint warnings:
```
  - Warning: qx.io.request.AbstractRequest (481, 15): Declared but unused variable or parameter: 'errorListener'
  - Warning: qx.io.request.AbstractRequest (483, 17): Declared but unused variable or parameter: 'failMessage'
```
Thank you! (It is always good to run `qx lint` before pushing).

**Comment by voger** [comment]
@cboulanger I am working on it now. Thanks for the qx lint advice. I wasn't aware of it.

**Review by hkollmann — APPROVED** [review]

File: framework/source/class/qx/io/request/AbstractRequest.js [hunk 1]
```diff
@@ -433,7 +431,7 @@ qx.Class.define("qx.io.request.AbstractRequest",
     */
     sendWithPromise: function(context) {
       if (qx.core.Environment.get("qx.promise")) {
-        var context =  (context !== undefined && context !== null) ?
+        context = (context !== undefined && context !== null) ?
```
Comment (derrell) [inline framework/source/class/qx/io/request/AbstractRequest.js]: More typically, this would be written as something like `context = context || this;` which is much simpler and easier to see what's going on. Is there a reason not to do that in this case?

**Review by derrell — APPROVED** [review]

**Review by derrell — CHANGES_REQUESTED** [review]
See inline comment

**Review by cboulanger — APPROVED** [review]

File: framework/source/class/qx/io/request/AbstractRequest.js (hunk 1 above)
Comment (voger) [reply framework/source/class/qx/io/request/AbstractRequest.js]: There is no particular reason for that. I was searching for what is the preferred way to set default function parameters in qooxdoo and it seemed more specific that way. 


I changed it and added two more tests for context binding. 


Another way would be using ES6 default function parameters so it would  be 
```javascript
sendWithPromise: function(context = this) {
```
but I have not seen it being used so far in framework's source so I was reluctant to use it.

**Review by level420 — APPROVED** [review]
@voger 👍 for integrating the case in the tests that promises are disabled or for other reasons unavailable

**Review by oetiker — APPROVED** [review]

File: framework/source/class/qx/io/request/AbstractRequest.js (hunk 1 above)
Comment (cboulanger) [reply framework/source/class/qx/io/request/AbstractRequest.js]: Since we still support the python compiler, which understands ECMA5 only, newer features are not yet allowed. So you did the right thing.

**Comment by voger** [comment]
@level420 Thanks. This was @hkollmann's idea.

**Review by derrell — APPROVED** [review]
