### PR TITLE
Fixed icon reset for selected node of TreeVirtual

### LINKED ISSUE #10607: Icon reset of selected button in TreeVirtual
**Describe the bug**
Pressing expand button leads to resetting icons of selected items in TreeVirtual.

**To Reproduce**
1. Go to [Playground example](https://tinyurl.com/yvseyr8u)
2. Click on Run
3. Select any node of Workplace folder
4. Press expand button of Network folder
5. The icon of selected node is changed to default icon.

**Expected behavior**
Icon of selected nodes have to keep their custom icons.

**Screenshots**
Снимок экрана от 2023-06-26 19-34-00

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 114

### PR DESCRIPTION
**Pull request by goldim**
Fixed #10607 

Please correct me. I think if the icon for a selected node is unset and usual icon is set then the selected node should have usual icon.

### CODE REVIEW

**Review by johnspackman — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

File: source/class/qx/ui/treevirtual/SimpleTreeDataCellRenderer.js [hunk 1]
```diff
@@ -408,7 +408,8 @@ qx.Class.define("qx.ui.treevirtual.SimpleTreeDataCellRenderer", {
       var node = cellInfo.value;
 
       // Add the node's icon
-      var imageUrl = node.bSelected ? node.iconSelected : node.icon;
+      var imageUrl =
+        bSelected && node.iconSelected ? node.iconSelected : node.icon;
```
Comment (derrell) [inline source/class/qx/ui/treevirtual/SimpleTreeDataCellRenderer.js:412]: This looks wrong. `bSelected` appears to be an undefined variable (unless it's global, which seems unlikely). Shouldn't that be `node.bSelected`?

**Review by derrell — CHANGES_REQUESTED** [review]

File: source/class/qx/ui/treevirtual/SimpleTreeDataCellRenderer.js (hunk 1 above)
Comment (goldim) [reply source/class/qx/ui/treevirtual/SimpleTreeDataCellRenderer.js:412]: Thank you, my bad. Looks like copied wrongly from one project to another to make commit.

**Review by derrell — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by level420 — APPROVED** [review]
