### PR TITLE
Simple table model sort methods fixed to handle null, undefined.

### LINKED ISSUE #10014: Sorting a table containing empty fields (null, undefined) does not work and produces holes
If I try to sort a table contining empty fields (null, undefined) by clicking on the column header, the empty fields appear as holes scattered around and not all in the end or in the beginning.

image

see playground example:
https://tinyurl.com/y68bob5f

The reason is that the comparison of null,undefined with other values in the default comparator:

https://github.com/qooxdoo/qooxdoo/blob/97418ba9a62fed5eb00efbbac5190fdde66ed24b/framework/source/class/qx/ui/table/model/Simple.js#L74

is not symmetric, so the native sorting algorithm produces garbage:

```js
"abc" > undefined == false     —>   return -1
undefined > "abc" == false     —>   return -1
```

This is similar to #3378 but for non-numeric columns

### PR DESCRIPTION
**Pull request by adrelino**
This fixes #10014.

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]

File: framework/source/class/qx/ui/table/model/Simple.js [hunk 1]
```diff
@@ -71,6 +71,8 @@ qx.Class.define("qx.ui.table.model.Simple",
           return result;
         }
       }
+      if(obj1==null && obj2!==null) return -1;
+      if(obj2==null && obj1!==null) return 1;
```
Comment (derrell) [inline framework/source/class/qx/ui/table/model/Simple.js:75]: These will match any falsy value of obj1 and obj2, e.g., `false` or `0`,  with `==`. The part before `&&` on lines 74 and 75 must use `===` instead of `==`.

Comment (derrell) [reply framework/source/class/qx/ui/table/model/Simple.js:75]: Similarly, in all cases below.

**Review by derrell — CHANGES_REQUESTED** [review]
I'm not convinced we should make this change, even with the requested changes. This has the potential to affect many existing apps. OTOH, this can be a potentially breaking change for 6.0, if well documented in the release notes...

File: framework/source/class/qx/ui/table/model/Simple.js (hunk 1 above)
Comment (adrelino) [reply framework/source/class/qx/ui/table/model/Simple.js:75]: > These will match any falsy value of obj1 and obj2, e.g., `false` or `0`, with `==`. The part before `&&` on lines 74 and 75 must use `===` instead of `==`.

No, thats wrong.

obj1==null will only return true if obj1 is null or undefined, which is exactly the check I intended to use.

Comment (adrelino) [reply framework/source/class/qx/ui/table/model/Simple.js:75]:
```js
console.log(null==0) // false
console.log(null==false) // false
console.log(null==null) // true
console.log(null==undefined) // true
```

Comment (johnspackman) [reply framework/source/class/qx/ui/table/model/Simple.js:75]: @derrell is this really a breaking change?  it sounds like the table sort works fine except when nulls are involved, in which case the sort order is random(ish) and undesirable in all cases

Comment (derrell) [reply framework/source/class/qx/ui/table/model/Simple.js:75]: @adrelino I stand corrected. Using `===` still seems prudent with falsy things, but I see that my statement was incorrect.

@johnspackman It's breaking only in that null was treated accidentally previously that is now explicit and possibly different.

I don't think it need be considered a breaking change.

**Review by derrell — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Comment by level420** [comment]
meging. Thank you @adrelino
