### PR TITLE
Fixes #9551: blur and deactivate widget before activating the blocker

### LINKED ISSUE #9551: Blocker does not block active/focused widget when blocker is attached to Composite
qx.ui.core.Blocker does not block active/focused widget when blocker is attached to qx.ui.container.Composite which contains that widget.

**To Reproduce**
1. Go to playground example: http://tinyurl.com/y862cwg7 
2. Type something into text field, then Press Enter. It will activate the Blocker which is attached to Composite that contains text field
3. See that you can still type into the widget, which is not correct. If now to click outside the text field to make it loose focus, it will get blocked as expected.

**Expected behavior**
Text field should get blocked immediately, so user cannot type anything into there anymore.

**Desktop:**
 - OS: Mac OSX, Windows 10
 - Tested in latest Chrome

### PR DESCRIPTION
**Pull request by ronkie**
blur and deactivate widget before activating the blocker

### CODE REVIEW

File: framework/source/class/qx/ui/core/Blocker.js [hunk 1]
```diff
@@ -263,13 +263,19 @@ qx.Class.define("qx.ui.core.Blocker",
...
+        activeWidget = qx.ui.core.Widget.getWidgetByElement(focusHandler.getActive()),
+        focusedWidget = qx.ui.core.Widget.getWidgetByElement(focusHandler.getFocus());
 
-      this.__activeElements.push(qx.ui.core.Widget.getWidgetByElement(focusHandler.getActive()));
-      this.__focusElements.push(qx.ui.core.Widget.getWidgetByElement(focusHandler.getFocus()));
+      this.__activeElements.push(activeWidget);
+      this.__focusElements.push(focusedWidget);
 
-      if (this._widget.isFocusable()) {
-        this._widget.focus();
```
Comment (oetiker) [inline framework/source/class/qx/ui/core/Blocker.js]: wouldn't this also automatically cause any other widget to blur?

Comment (ronkie) [reply framework/source/class/qx/ui/core/Blocker.js]: The problem is that when blocker is attached to a composite, this piece of code is not doing anything, because composite is not focusable.

**Review by hkollmann — COMMENTED** [review]
could we have the var in single lines? IMHO is better readable.

var focusHandler = qx.event.Registration.getManager(window).getHandler(qx.event.handler.Focus);
var  activeWidget = qx.ui.core.Widget.getWidgetByElement(focusHandler.getActive());
var  focusedWidget = qx.ui.core.Widget.getWidgetByElement(focusHandler.getFocus());

**Review by oetiker — DISMISSED** [review]

**Comment by ronkie** [comment]
Put variables into single lines, as requested by @hkollmann

**Review by hkollmann — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Comment by cajus** [comment]
This PR breaks *readonly* Textfields in combination with Blockers.
