### PR TITLE
use promises only if qx.promise is true

### LINKED ISSUE #9576: "qx.promise" Environment setting has no effect
the "qx.promise" flag has been introduced to be able to remove the complete `qx.Promise`-Class and its dependencies to save some KB in the build size.

This does not work anymore. At least the DynamicScriptLoader uses `qx.Promise` without checking if its enabled: https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/util/DynamicScriptLoader.js#L149

There might be other places where the "qx.promise"-flag should be checked.

### PR DESCRIPTION
**Pull request by peuter**
closes #9576

### CODE REVIEW

**Review by oetiker — DISMISSED** [review]

File: framework/source/class/qx/util/DynamicScriptLoader.js [hunk 1]
```diff
@@ -143,24 +143,36 @@ qx.Class.define("qx.util.DynamicScriptLoader", {
 
     /**
      * Start loading scripts. This may only be called once!
-     * @return {Promise} a promise which will be resolved after load of all scripts.
+     * @return {Promise|null} a promise which will be resolved after load of all scripts if promises are enabled or null if not.
```
Comment (derrell) [inline framework/source/class/qx/util/DynamicScriptLoader.js]: It appears this documentation is incorrect. I don't see anyplace that returns `null`; rather, line 167 simply does `return;` so the return value is `undefined`, not `null`. Either the documentation here should be corrected, or line 167 should be changed to `return null;`.

**Review by derrell — CHANGES_REQUESTED** [review]
see embedded comments

**Review by derrell — DISMISSED** [review]

**Review by johnspackman — DISMISSED** [review]

File: framework/source/class/qx/util/DynamicScriptLoader.js [hunk 2]
```diff
@@ -143,24 +143,36 @@ qx.Class.define("qx.util.DynamicScriptLoader", {
 
     /**
      * Start loading scripts. This may only be called once!
-     * @return {Promise} a promise which will be resolved after load of all scripts.
+     * @return {Promise?} a promise which will be resolved after load of all scripts if promises are enabled.
```
Comment (cboulanger) [inline framework/source/class/qx/util/DynamicScriptLoader.js]: Shouldn't it document what it returns if promises are NOT enabled? Sp that the API consumer knows how to code against this?

Comment (peuter) [reply framework/source/class/qx/util/DynamicScriptLoader.js]: But it doesn't return anything if promises are NOT enabled. It only returns something (a promise) if promises are enabled and that is documented.

Comment (derrell) [reply framework/source/class/qx/util/DynamicScriptLoader.js]: Since it was unclear to one person, it may be unclear to others, too. Maybe change the documentation for that return value to,
```
a promise which will be resolved after load of all scripts if promises are enabled, if promise support is enabled; nothing (undefined) if promises are not enabled.
```

**Review by hkollmann — DISMISSED** [review]

File: framework/source/class/qx/util/DynamicScriptLoader.js (hunk 2 above)
Comment (cboulanger) [reply framework/source/class/qx/util/DynamicScriptLoader.js]: I don't insist - it wasn't clear to me that the JSDOC "{Promise?}" means "{Promise|undefined}" but if it does, that should be enough.

**Review by cboulanger — DISMISSED** [review]

File: framework/source/class/qx/util/DynamicScriptLoader.js (hunk 2 above)
Comment (peuter) [reply framework/source/class/qx/util/DynamicScriptLoader.js]: Well I think @derrel is right: it is better to mention the `undefined` return explicitly.

**Review by cboulanger — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by cajus — APPROVED** [review]

**Review by oetiker — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by derrell — APPROVED** [review]
