### PR TITLE
Issue #9245: Fix spinner focus handling

### LINKED ISSUE #9245: Spinner Focus problem
Hi all,
I think, there is a problem with Spinner object when we use the method '.focus()'.
The object seems to receive the focus but we can't use the keyboard in order to change the value.
(ok with tab key)

Example:
```
// Create a button
var button1   = new qx.ui.form.Button("First Button", "icon/22/apps/internet-web-browser.png");
var mySpinner = new qx.ui.form.Spinner(0, 0, 99);

// Document is the application root
var doc = this.getRoot();

// Add button to document at fixed coordinates
doc.add(button1,   {left : 100, top  : 50});
doc.add(mySpinner, {right: 100, top  : 50});

// Add an event listener
button1.addListener("execute", function(e) {mySpinner.focus();});
```

### PR DESCRIPTION
**Pull request by cajus**
Do the focus handling more or less analogue like it's done in the DateField.

Fixes #9245

### CODE REVIEW

**Review by patrick-fischer-hirschstein — APPROVED** [review]

File: framework/source/class/qx/ui/form/Spinner.js [hunk 1]
```diff
@@ -118,6 +118,17 @@ qx.Class.define("qx.ui.form.Spinner",
     } else {
       this.initValue();
     }
+
+    // forward the focusin and focusout events to the textfield. The textfield
+    // is not focusable so the events need to be forwarded manually.
+    this.addListener("focusin", function(e) {
+      textField.fireNonBubblingEvent("focusin", qx.event.type.Focus);
+      textField.selectAllText();
```
Comment (level420) [inline framework/source/class/qx/ui/form/Spinner.js]: I think selecting all text in the textfield is inconsistent with other widgets like combobox and datefield where only a focus caused by a tab selects all text.

See http://tinyurl.com/zfxldfl

**Review by level420 — CHANGES_REQUESTED** [review]

File: framework/source/class/qx/ui/form/Spinner.js (hunk 1 above)
Comment (cajus) [inline framework/source/class/qx/ui/form/Spinner.js]: Yeah. Will change it back.

Do you have an idea why it is this way?  I don't see why tab selection differs from click selection.

**Comment by cajus** [comment]
@level420 do you've an idea why it is that way? The tab/click focus difference feels inconsistent to me.

File: framework/source/class/qx/ui/form/Spinner.js (hunk 1 above)
Comment (cajus) [inline framework/source/class/qx/ui/form/Spinner.js]: I personally would prefer a "cursor after text" in all textfield related widgets.

**Comment by level420** [comment]
@cajus I think this is simply due to different people with different os and ui background implemented different behavior.

I think it would be good to have this consistent.

**Comment by level420** [comment]
What I wouldn't expect to happen, is that if I focus the textfield via a pointer click all text gets selected. I would expect the cursor to be placed at the mouse click position.

File: framework/source/class/qx/ui/form/Spinner.js (hunk 1 above)
Comment (johnspackman) [inline framework/source/class/qx/ui/form/Spinner.js]: i think tab vs click differs because it's designed around larger text input areas - EG with a click, the implication is that you could be positioning the cursor at the same time as adding focus, and if you had a long text field or multi-lone text area that could be important; when using tab, the idea is that you are tabbing through a form filling in each field, so select-all is useful so that you can review and quickly replace the content.

**Comment by cajus** [comment]
So we've to define what "constistent" is, actually. I've commited the "cursor before text" like in DateField now. If we'd go for "cursor after text", both - the Spinner and the DateField - need a change.

**Comment by level420** [comment]
focus on tab -> select all
focus on click -> place cursor at click position
programmatic focus -> I'm not sure, but maybe also select all

**Comment by johnspackman** [comment]
programmatic focus should not select-all, otherwise you can't switch focus away and then back again eg to a popup

**Comment by level420** [comment]
combobox does not set the selection at all: https://github.com/qooxdoo/qooxdoo/blob/master/framework/source/class/qx/ui/form/ComboBox.js#L57-L59

This way the cursor positioning is done (I guess) the OS or browser way, which at least on windows is positioning the cursor at the end of the text.

So for me the fix would be to not do any cursor positioning, selection at all:
```javascript
    this.addListener("focusin", function(e) {
      textField.fireNonBubblingEvent("focusin", qx.event.type.Focus);
    }, this);
```

**Comment by level420** [comment]
this should also be fixed in datefield.

**Comment by cajus** [comment]
If you leave out the text selection in the spinner, the cursor will not jump in on programatic focus. I guess that the combo box will suffer from the same problem.

**Comment by cajus** [comment]
They're overriding `focus()` in the combo box to make it work. That is also inconsistent.

**Comment by cajus** [comment]
So either, we're going to override `focus()` in Spinner/DateField and remove the text selection from the handler, or keep the text selection and do not override `focus()` ;-)

**Comment by cajus** [comment]
Can push that for DateField and Spinner. So all widgets I looked at, place the cursor *after* the text on programatic focus.

**Comment by cajus** [comment]
If I recall correctly, that was my first try and it went red in travis - but lets wait for it...

**Comment by level420** [comment]
So here is a playground sample showing the different textfield based widgets with the behavious before this PR:

http://tinyurl.com/hl462ba

**Comment by cajus** [comment]
And this one after:

http://tinyurl.com/z68999c

Not that it shows a different behaviour on Chrome/Firefox. Firefox puts the cursor *before* and Chrome *after* the text ;-)

**Comment by level420** [comment]
@cajus Firefox puts the cursor on windows _after_ the text. So it's OS dependent with firefox. IE puts the cursor after the text.

**Comment by cajus** [comment]
So - whatever - it's quite not consistent over the OSses, but it's now consistent in itself.

**Comment by level420** [comment]
hmmm not on safari OSX. while all other widgets put the cursor after the text, the textarea places it _before_ the text.

**Comment by cajus** [comment]
... which is maybe out of focus for this issue and may be just a bug in Safari. It would not be the first I've spotted there.

**Comment by cajus** [comment]
Or we start to implement  forced "after text" for all browsers in all text widgets.

**Comment by level420** [comment]
After testing on OSX I'd be in favor of forcing a consistent "force cursor after text" on focus for all platforms.

But we should discuss this.

**Comment by derrell** [comment]
Note that any change here will be a backward-compatibility-breaking change so must go into a major release. Either that, or we should provide a function that fixes these things and have the next major version call that function by default.

**Comment by level420** [comment]
@derrell at least the fix for the spinner is a bug fix imho. I don't think it breaks backward compatibility if we fix it.

The same applies for me with datefield, as it reacted inconsistent for some platforms/browsers by not doing the default, but forcing it o set the cursor at the beginning of the text.

So I would then say ot merge the PR as it is now.

**Review by level420 — APPROVED** [review]

**Comment by level420** [comment]
The forced unification for all platforms should be a separate PR then.

**Comment by derrell** [comment]
@cajus If we are sure that everyone would consider it a bug fix then sure, merge as is. If not, it should wait for a major release. I'm good with whichever decision the team makes on this.

**Comment by cajus** [comment]
It's a bug fix. Everything else (the fact that it behaves differently on certain browsers/os'es) is stuff that is/was broken all the time.

**Review by johnspackman — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Comment by level420** [comment]
3 approvals, more than 2 business days
merging
thank you @cajus
