### PR TITLE
Desktop dispose fix

### LINKED ISSUE #10622: Dispose desktop widget leads to an error
**Describe the bug**
Flushing `qx.ui.window.Manager` is broken.

**To Reproduce**
1. Go to Playground
2. Open browser console
3. Paste next code:
```javascript
var mainwin = new qx.ui.window.Window("Main Window");
const mainDes = new qx.ui.window.Desktop(new qx.ui.window.Manager());
mainDes.add(mainwin);
this.getRoot().add(mainDes, {left:20, top:20});
mainDes.dispose();
```
4. Press Run
5. See error

**Desktop (please complete the following information):**
 - Qooxdoo Version [7.6.1]

**Error message**
```
003753 qx.ui.core.queue.Widget: Error in the 'Widget' queue:TypeError: this.__P_558_0 is null TypeError: this.__P_558_0 is null
```
Instead of `this.__P_558_0` locally got `__desktop` in my app.

### PR DESCRIPTION
**Pull request by goldim**
There are tightly coupled classes: `qx.ui.window.Desktop` and `qx.ui.window.Manager`. In destructor of Desktop there is disposing of Manager and vice versa. There is a case when desktop could be disposed firstly BUT `syncWidget` of Manager uses desktop member and leads to an error.

It is a fast and straightforward solution If you know better one just let me know. Thanks.

### CODE REVIEW

File: source/class/qx/ui/window/Manager.js [hunk 1]
```diff
@@ -81,6 +81,9 @@ qx.Class.define("qx.ui.window.Manager", {
      * {@link qx.ui.core.queue.Widget widget queue}.
      */
     syncWidget() {
+      if (!this.__desktop){
```
Comment (derrell) [inline source/class/qx/ui/window/Manager.js:84]: A much more typical way of handling this type of issue in qooxdoo, is:

```
      if (this.isDisposed()) {
        return;
      }
```

**Review by derrell — CHANGES_REQUESTED** [review]

File: source/class/qx/ui/window/Manager.js (hunk 1 above)
Comment (goldim) [reply source/class/qx/ui/window/Manager.js]: It looks much better! Tested it, does work.

**Review by hkollmann — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Review by cboulanger — APPROVED** [review]

**Review by derrell — APPROVED** [review]

**Review by oetiker — APPROVED** [review]
