### PR TITLE
use image size for Boolean table cell render, up to max (and default) 11x11

### LINKED ISSUE #9646: Regression with images in Table
Reference commit 0937f6c9ef8bf14ca05a9f778001b8d9290b0804: Add support for hi-res images to AbstractImage cellrenderer (#9625)

The correct  behavior and new, incorrect can be seen in these two images. The incorrect behavior was introduced with the above commit.

### PR DESCRIPTION
**Pull request by derrell**
Fixes #9646. An image in the Boolean cell renderer was traditionally placed in an 11x11px box regardless of actual image size, and placed starting at the top-right corner of that 11x11px box. With the recent changes proposed in #9610 and merged in #9625, images smaller than 11x11 used in the Boolean cell renderer were stretched to fit the 11x11 box, causing a backward-compatibility break.

This change attempts to retrieve the actual image size, and use that size for the Boolean indication. If the actual image size can't be determined, as might be the case with an unmanaged image, the original 11x11 size is used.

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]

**Review by hkollmann — APPROVED** [review]

File: framework/source/class/qx/ui/table/cellrenderer/Boolean.js [hunk 1]
```diff
@@ -131,12 +131,39 @@ qx.Class.define("qx.ui.table.cellrenderer.Boolean",
...
+      }
+
+      // Create the size portion of the hint.
+      //
+      // The traditional (fixed) size of the image was 11x11px. Use that if we
+      // weren't able to retrieve the actual size of the image, and never
+      // exceed that size.
+      imageHints =
+      {
+        imageWidth  : w ? Math.min(w, 11) : 11,
```
Comment (oetiker) [inline framework/source/class/qx/ui/table/cellrenderer/Boolean.js]: this means there can never be a boolean image larger than 11 pixel in size ?

Comment (derrell) [reply framework/source/class/qx/ui/table/cellrenderer/Boolean.js]: It means that if the image size is larger than 11x11, we revert to using the prior behavior of specifying 11x11. I believe this is the best backward-compatibility solution. Previously, it was hard-coded at 11x11, so with this change, images smaller than 11x11 render correctly even with the addition of the #9610 changes.

Comment (oetiker) [reply framework/source/class/qx/ui/table/cellrenderer/Boolean.js]: as a theme developer, this seems very wrong to me ... having icons forcefully rescaled to 11x11 pixel ... one shudders ... I would suggest du dop this whole thing and just check that our existing themes look ok .... apart from that, let people shoot themselves. silently resizing seems extremely wrong.

Comment (cboulanger) [reply framework/source/class/qx/ui/table/cellrenderer/Boolean.js]: But isn't @derrell argument that we just need to make sure things work as expected while accommodating @jpriebe's patch? As far as I understand the icon was force resized to 11x11 before, too. That might be a bad idea, but at least is B/C. Or did I misunderstand something?

Comment (derrell) [reply framework/source/class/qx/ui/table/cellrenderer/Boolean.js]: @cboulanger is exactly correct. The code is currently broken. Images smaller than 11x11 used to work fine, but are now being stretched and look awful. This code is trying to make things work like they did before, without introducing new, non-BC changes.

It is trivial to subclass the Boolean cell renderer and override that one method, if a different behavior is desired. Anyone who needed larger images previously would have already done that.

Comment (cboulanger) [reply framework/source/class/qx/ui/table/cellrenderer/Boolean.js]: @oetiker Would it be ok to accept this state for v6 and put the correction on the list of breaking changes for v7.0?

Comment (oetiker) [reply framework/source/class/qx/ui/table/cellrenderer/Boolean.js]: sure as you wish ...

**Review by oetiker — APPROVED** [review]

**Review by johnspackman — APPROVED** [review]

**Review by level420 — APPROVED** [review]

**Comment by cboulanger** [comment]
5 approvals, merging, thank you, @derrell !
